on:
  push:
    branches:
      - main
  schedule:
    - cron: "9 2 * * *"
# Do not attempt concurrent runs.
concurrency:
  group: ${{ github.workflow }}
jobs:
  jjjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment.
        with:
          key: ${{ hashFiles('pyproject.toml', 'uv.lock', '.python-version') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Run!
          pipx run \
            uv run --no-dev -m \
              jjjquery
      # Scrape if scheduled run.
      - if: ${{ github.event_name == 'schedule' }}
        run: |
          # Git scrape! https://simonwillison.net/tags/git-scraping/
          pipx run \
            uv run --no-dev -m \
              jjjquery >> jjjquery.log

          # Set git user details to look like this:
          # schedule (cron: "9 2 * * *") <1658821493@octocat/hello-world/.github/workflows/my-workflow.yml@refs/heads/my_branch>
          git config user.name "$GITHUB_EVENT_NAME (cron: \"${{ github.event.schedule }}\")"
          git config user.email "$GITHUB_RUN_ID@$GITHUB_WORKFLOW_REF"

          # Commit scraped data with link to workflow run and push.
          git add jjjquery.log
          git commit -m "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" || exit 0
          git push
